compiler-explorer/misc-builder

Dockerfile
build/buildTenDRA.sh

* Upgrades to 20.04 (may cause downstream issues later, but for now...)
* Installs a bunch of i386 stuff
* Attempts to build and bootstrap TenDRA
Currently fails with:
```
==> Linking src/tld
/root/tendra/obj.89e5dd28d211-bootstrap/bin/tcc  -o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/tld /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/_partial/src/shared/_partial.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/_partial/src/exds/_partial.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/_partial/src/adt/_partial.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/_partial/src/frontend/_partial.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/arg-parse.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/debug.o /root/tendra/obj.89e5dd28d211-rebuild/obj/tld/src/file-name.o …
```

Work in progress on TenDRA

---

build/build-mrustc.sh

Add builder for mrustc.
This is currently needed because mrustc does not provide binary snapshot for its
releases (and also because mrustc until recently would always invoke the local C
compiler as its last step, which is not wanted).
refs #2643

Initial support for mrustc build

---

Dockerfile
build/build-rustc-cg-gcc.sh

rustc can use different backend and this new script builds all the needed parts
to have GCC as the code generator.
It needs (at the moment) a patched version of GCC and builds it with libjit support.
Some glue code (in Rust) is added in the mix to finally be able to use the rustc
compiler with this dynamic backend.
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/2683

Initial support for rustc_codegen_gcc

---

build/build-cproc.sh
build/build-mrustc.sh
build/build-rustc-cg-gcc.sh

Make the last revision argument optional for easier local use.
Change git URL for rustc_cg_gcc as it's now part of rust-lang:
https://github.com/rust-lang/rust/pull/87260
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

Minor change in cproc, mrustc and rustc_cg_gcc

---

build/build-dotnet.sh

cc @hez2010 @partouf 
This puts into the docker everything we need for fast (~1s) "change C#/F#/VB.NET -> observe codegen" loop.
the content of the root folder is:
```
[crossgen2] - contains crossgen binary with checked jits
[.dotnet] - bootstrap .NET SDK for "dotnet build -c Release --no-restore" command for user's code
[testapp] - prebuilt "Class Library" empty app
*.* - base class libraries needed for prejitting
```
The loop (for e.g. C#) should look like this:
1) User writes C# code directly to `csapp/Class1.cs`
2) Build user's code:
```
DOTNET_TC_QuickJitForLoops=1 ./.dotnet/dotnet build csapp -c Release -o csapp/out /p:AllowUnsafeBlocks=true --no-restore --no-dependencies --nologo
```
3) Prejit using crossgen2:
```
DOTNET_TC_QuickJitForLoops=1 ./.dotnet/dotnet …
```

Improve .NET bits for faster compilation

---

Dockerfile
build/build-jakt.sh

Jakt currently needs to be build using Rust. So download a rust release
from infra.
And the ce_install for Rust needs patchelf under /opt/compiler-explorer,
so symlink it there.
Note: Installing a Rust version using infra currently downloads that version for all architectures that Rust supports, which is way overkill here. But as far as I can tell, there's currently no way to configure the architectures that are downloaded in infra. If I just missed how to do that, please tell me.

Build the jakt programming language

---

build/build-jakt.sh

This should fix https://github.com/compiler-explorer/misc-builder/pull/40 so that cargo is found in the Jakt build script.
cc @partouf

Jakt: Add cargo to path before build

---

build/build-jakt.sh

So they are actually put in the output tar file

Jakt: Put artifacts into staging dir

---

build/build-rustc-cg-gcc.sh

After some change (probably in rustc_cg_gcc?), the correct libgccjit can't be found by the dynamic loader:
error: couldn't load codegen backend "librustc_codegen_gcc.so": libgccjit.so.0: cannot open shared object file: No such file or directory
even with the library correctly installed along the backend.
Patching the lib's RPATH with patchelf fixes this issue.
fixes #4047
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

Fix rustc_cg_gcc build

---

build/build-rocm-hip.sh

This changes the paths in generated tarball from
opt/compiler-explorer/libs/rocm/5.2.3/*
to
./hip-amd-rocm-5.2.3/*
to match the default expectations for library tarballs in infra. I think this should let me drop the `untar_dir: opt/compiler-explorer/libs/rocm/{{name}}` from https://github.com/compiler-explorer/infra/pull/834.

Fix ROCm tarball paths

---

Dockerfile

I believe this change will enable building HIP for ROCm 5.3.2 with `./build-rocm-hip.sh 5.3.2`. Though, first the clang-builder must be run with `./build.sh rocm-5.3.2` so that there is an S3 tarball for the compiler.
EDIT: I originally opened this PR for ROCm 5.3.1, but it turns out that version will never have a full release due to an issue found right after tagging. I'll mark this PR as ready when ROCm 5.3.2 has released.

Add rocm-5.3.2 compiler to image

---

Dockerfile

-> to enable interaction-less clone from within a container. 
Docker build hangs otherwise (if run from scratch, not relying on pre-existing layers).

Add github public key to known_hosts

---

build/build-rocm-hip.sh

Prior to ROCm 5.3, the profiling API was being gracefully disabled by default, possibly because libroctracer was not found at configure time. However, in ROCm 5.3, a new dependency on CppHeaderParser was added for building the profiling API and its absence was treated as a fatal error.
@RubenRBS, this should fix the issue you mentioned in https://github.com/compiler-explorer/infra/pull/857.

Explicitly disable HIP Profiling API

---

build/build-dotnet.sh

with `-ci` and `-p:OfficialBuildId=<seed>`, we get the proper version info in compiled binaries out of dotnet's build infrastructure:
```sh
for v in trunk v7.0.0 v6.0.11; do
rm -rf dotnet
sh build/build-dotnet.sh $v
dotnet/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/crossgen2/crossgen2 --version
done
```
before (no `-p:OfficialBuildId=`):
```
8.0.0-dev
7.0.0-dev
```
after (with `-ci` and `-p:OfficialBuildId=`):
```
8.0.0-alpha.1.22579.99+4b9e3c0f72416de5fc40cc6fb21974967542d5ad
7.0.0-rtm.22579.99+d099f075e45d2aa6007a22b71b45a08758559f80
```
in 6.0, crossgen2 doesn't have `--version` option so i've manually written version.txt in the tarball for fallback.
@mattgodbolt, @partouf, next, i'll update compiler-explorer/compiler-explorer  to display on first line as comment …

build dotnet as "official"

---

build/build-spirv-tools.sh

utils/update_build_version.py needs tag to run. Cloning with `--depth 1` does not get them, and then produce an error when building spirv-tools.
removing `--depth 1` allows to get tag and fix the build of spirv-tools

build-spirv-tools.sh: remove depth while cloning to get needed tags

---

build/build-dotnet.sh

the trunk build started to fail on jan 12 when https://github.com/dotnet/runtime/commit/2ca7cf7140ebfaa8e34732b529c194416b122e89 was merged.
it needs lower-case OS name for versions > 7

fix dotnet build

---

misc/build-dxc.sh

This works around the DXC 1.8 preview build having non-conformant code by passing `-fpermissive` to gcc.
Fixes #73

Workaround non-conformant C++ in 1.8 preview

---

Dockerfile.pythran
pythran/build.sh
pythran/scratch/meta.yaml

The build is a bit atypical. In order to get a
self-sufficient/relocatable "compiler", we use the conda package... But we cheat a bit by faking its dependencies on a c++ compiler. The conda package has its own dep and will insteall its own copy of gcc/clang... But we have plenty of C++ compilers, so all the gcc deps are stubbed. Pythran knows how to look for g++ using CXX or by relying on PATH.
refs https://github.com/compiler-explorer/compiler-explorer/issues/6079

Initial support for pythran

---

hylo/build.sh

Set version/commit hash in the build
Without this step ``hc --version`` always returns ``unknown``
https://github.com/hylo-lang/hylo/pull/1434
This is performed in hylo's CI/CD pipeline but since we do a manual build, it has to be explicitly performed.
This might be helpful when reporting issues to hylo or CE.

Update build.sh; introduce version

---

Dockerfile.hylo
README.md
hylo/build.sh

This MR hopefully fixes the build for the Hylo compiler by updating swift version to 5.10.
I also updated the README.md because I got confused for a moment by skipping `docker build` entirely by just seeing there is an alternative to run (and for run, I just wrongly assumed it includes the whole previous section).

Update Swift for hylo to version 5.10

---

rocm/build.sh
rocm/patches/hipamd-rocm-6.0.2-0001-fix-cmake

Change github URL name to ROCm.
Get device libs, comgr and hipcc from llvm for ROCm 6.1 and above.
Make the script work for ROCm version above 5.7.

Update build script for rocm

---

rocm/build.sh

Install device libs to /opt/compiler-explorer/libs/rocm/6.1.2 instead of /opt/compiler-explorer/clang-rocm-6.1.2 since somehow device libs built by rocm/build.sh for rocm 6.1.2 are not added to clang-rocm-6.1.2 zip file.
/opt/compiler-explorer/libs/rocm/6.1.2 is the location for device libs in the official rocm build any way. This can also avoid --rocm-device-lib-path since --rocm-path will be sufficient to find the device libs.

Fix rocm/build.sh

---

rocm/build.sh

we still need to install device libs to the compiler directory since rocm build needs it to be there, but we copy them to rocm directory.

Fix rocm 6.1.2 comgr build

---

misc/build-cppfront.sh

https://github.com/compiler-explorer/compiler-explorer/issues/6721
I don't have an environment set up to test this, so hopefully this is at least helpful.

Copy all headers to fix cpp1 build on cpp2.godbolt.org

---

hylo/build.sh

The temporary fix is no longer needed; it has been upstreamed to the main repo. Thanks @tothambrus11 for the original fix!

Point build.sh back to main Hylo repository

---

.github/workflows/build.yml
Dockerfile.clad
clad/build.sh

Build clad

---

Dockerfile.c2rust
c2rust/build.sh

Resolves https://github.com/compiler-explorer/compiler-explorer/issues/7592.
`c2rust` needs a complete working clang installation, so compiling against the system clang and copying the clang/LLVM `.so`s means that `c2rust` will not find some system headers. This PR builds `c2rust` against a clang that is available on CE instead.
Requires https://github.com/compiler-explorer/compiler-explorer/pull/7696 because clang’s `lib/` dir is not in the default library search path.

Build c2rust against a clang that is available on CE

---

Dockerfile.miri
miri/build.sh

Miri needs a special pre-built standard library which is normally built on-demand when using `cargo miri` and cached locally. This standard library needs to match the exact nightly version of the compiler. The rest of Miri is already installed by `./bin/ce_install ...`.
This PR builds this sysroot for all architectures. If this is too much (due to storage/build time requirements), this could be restricted to the more common architectures.
Because the sysroot/standard library version must exactly match the compiler version, this build includes the full Rust `nightly` compiler (so there are no conflicts depending on when Miri and Rust `nightly` are updated on the runners).
Building the sysroot needs the Rust standard library sources, so this PR requires …

Build Miri for Rust
