build/build-mrustc.sh

Check $3 for last build revision and skip if nothing has changed.
fixes #5

Fix mrustc builder to be able to skip already build revision

---

build/build-cproc.sh

cproc is a very lightweight C compiler that uses QBE backend:
https://github.com/michaelforney/cproc
https://github.com/compiler-explorer/compiler-explorer/issues/2755
fixes #2755

Support for cproc compiler

---

build/buid-chibicc.sh

This is based on
https://github.com/compiler-explorer/misc-builder/pull/9 (Thanks @dkm!)
For issue https://github.com/compiler-explorer/compiler-explorer/issues/2639
This is a PR because I don't know if what it does is correct, so I need someone to doublecheck :)
Also, as far as I can tell, licensing is ok in this one

Adds main build for chibicc

---

Dockerfile
build/build-spirv-tools.sh

This PR adds support for [SPIR-V Tools](https://github.com/KhronosGroup/SPIRV-Tools).
I've done this change in the same way as #13, so may need to make changes based off any feedback on that PR as well.

Add support for SPIR-V Tools

---

Dockerfile
build/build-clspv.sh

This PR adds support for building the [clspv](https://github.com/google/clspv) compiler.
I'm not 100% sure that I've done this correctly... so any feedback is welcome :)

Add support for clspv compiler

---

Dockerfile
build/build-dotnet.sh

Add .NET CoreCLR build script

---

Dockerfile
build/build-dotnet.sh

Use en_US.UTF-8 for locale

---

build/build-rustc-cg-gcc.sh

fixes #3256
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

Fix tar for rustc cg gcc

---

build/build-dotnet.sh

Fixes https://github.com/compiler-explorer/misc-builder/pull/27#issuecomment-1043315647 build failure

Ignore dotnet/runtime's analyzers

---

build/build-dotnet.sh

Fix build-dotnet.sh #2

---

build/build-rustc-cg-gcc.sh

The build instruction have changed, see:
https://github.com/rust-lang/rustc_codegen_gcc#building
for up to date ones.
fixes https://github.com/compiler-explorer/compiler-explorer/issues/3625
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>

Fix rustc_codegen_gcc build

---

Dockerfile
build/build-z88dk.sh

Does not work yet, tried to install boost via conan and pass it onto pkg-config, but it appears the SDCC configure script does not see/use pkg-config

attempt to resolve dependencies for z88dk

---

build/build-dxc.sh

To test this script, I ran the image build and the script locally via Docker WSL2 and confirmed a successful build + archive.

Add build-dxc.sh for the DirectXShaderCompiler

---

build/build-dotnet.sh

Only keep Core_Root in the tarball.

Update artifacts path in dotnet tarball

---

build/build-compcert.sh

CompCert must have the same path as in infra for libraries
I just added /compcert to $OPT

Change of location of CompCert

---

rocm/build.sh

For https://github.com/compiler-explorer/compiler-explorer/pull/5569

Update rocm build script for ROCm 5.7.0 support

---

rocm/build.sh
rocm/patches/ROCm-Device-Libs-rocm-5.7.0-0001-fix-device-libs.sh
rocm/patches/hipamd-rocm-5.7.0-0001-fix-cmake

Fix build for ROCm 5.7.0

---

vast/build.sh

vast: fix installation

---

.github/workflows/build.yml
Dockerfile.heaptrack
heaptrack/build-cross.sh
heaptrack/build.sh

Currently stuck at trying to compile elfutils for aarch64, it gives errors for zlib and I can't figure out how to tell it where to find it.

attempt to crosscompile heaptrack

---

.github/workflows/build.yml
Dockerfile.python
python/build.sh

Closes compiler-explorer/python-builder#3

Adds python

---

.github/workflows/build.yml
Dockerfile.lfortran
lfortran/build.sh

See https://github.com/compiler-explorer/compiler-explorer/pull/7119

Add build for lfortran

---

clad/build.sh

```
bollo:/t/out $ ls clad-1.8-clang-18.1.0
include/  lib/
```

Copy includes and support clang versions

---

python/build.sh

Grab _all_ dependent SOs, not just the OpenSSL ones. Helps with finding ctypes, see compiler-explorer/infra#1530 and compiler-explorer/compiler-explorer#7405.
CC @Rupt - this is how we make some of our other compilers "hermetic" as in at least any SOs they need (other than bare system ones) are copied into the output binary and shipped along (sort of like static linking but without the static bit)
Tested locally and the `import ctypes` works (and I showed it reproducibly broke prior to this change).
Would need a rebuild and reinstall of all pythons.

A more principled approach to SOs for python

---

Dockerfile.c2rust
c2rust/build.sh

Closes https://github.com/compiler-explorer/compiler-explorer/pull/7696.

[c2rust] Add required clang to `RPATH`

---

clad/build.sh

fixing: https://github.com/compiler-explorer/misc-builder/issues/115
cc @vgvassilev

disable tests in clad (disabling kokkos)
